# This is a basic workflow to help you get started with Actions

name: Docker push and build CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Docker Login
        env:
          DOCKER_ID: ${{secrets.DOCKER_ID}}
          DOCKER_PSWD: ${{secrets.DOCKER_PSWD}}
        run: |
          docker login -u $DOCKER_ID -p $DOCKER_PSWD
          
      - name: Docker Build Step
        run: |
          docker build ./ -t ahmadobeid/micro-service:latest
      - name: Docker Push Step
        run: |
          docker push ahmadobeid/micro-service:latest:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ml-micro-service"
          heroku_email: "ahmadkobrid96@gmail.com"
          usedocker:  1
          dontuseforce: 1

